import { Component, OnInit } from '@angular/core';
import { SalesPerson } from './sales-person';

@Component({
  selector: 'app-sales-person-list',
  templateUrl: './sales-person-list-bootstrap.component.html',
  styleUrls: ['./sales-person-list.component.css']
})
export class SalesPersonListComponent implements OnInit {

  salesPersonList: SalesPerson[] = [
    new SalesPerson('Alice', 'Johnson', 'alice.johnson1@example.com', 5023),
    new SalesPerson('Bob', 'Smith', 'bob.smith2@example.com', 7130),
    new SalesPerson('Charlie', 'Brown', 'charlie.brown3@example.com', 6112),
    new SalesPerson('David', 'Wilson', 'david.wilson4@example.com', 8420),
    new SalesPerson('Eva', 'Martinez', 'eva.martinez5@example.com', 4590),
    new SalesPerson('Frank', 'Garcia', 'frank.garcia6@example.com', 9780),
    new SalesPerson('Grace', 'Lee', 'grace.lee7@example.com', 1200),
    new SalesPerson('Hannah', 'Walker', 'hannah.walker8@example.com', 3325),
    new SalesPerson('Ian', 'Hall', 'ian.hall9@example.com', 15400),
    new SalesPerson('Julia', 'Allen', 'julia.allen10@example.com', 2890),
    new SalesPerson('Kevin', 'Young', 'kevin.young11@example.com', 7600),
    new SalesPerson('Laura', 'Hernandez', 'laura.hernandez12@example.com', 4985),
    new SalesPerson('Michael', 'King', 'michael.king13@example.com', 13500),
    new SalesPerson('Nina', 'Wright', 'nina.wright14@example.com', 2500),
    new SalesPerson('Oscar', 'Lopez', 'oscar.lopez15@example.com', 6420),
    new SalesPerson('Paula', 'Hill', 'paula.hill16@example.com', 3777),
    new SalesPerson('Quentin', 'Scott', 'quentin.scott17@example.com', 8900),
    new SalesPerson('Rita', 'Green', 'rita.green18@example.com', 4050),
    new SalesPerson('Sam', 'Adams', 'sam.adams19@example.com', 2200),
    new SalesPerson('Tina', 'Baker', 'tina.baker20@example.com', 15750),
    new SalesPerson('Uma', 'Nelson', 'uma.nelson21@example.com', 6900),
    new SalesPerson('Victor', 'Carter', 'victor.carter22@example.com', 5400),
    new SalesPerson('Wendy', 'Mitchell', 'wendy.mitchell23@example.com', 3100),
    new SalesPerson('Xavier', 'Perez', 'xavier.perez24@example.com', 9250),
    new SalesPerson('Yara', 'Roberts', 'yara.roberts25@example.com', 4800),
    new SalesPerson('Zane', 'Turner', 'zane.turner26@example.com', 7700),
    new SalesPerson('Aaron', 'Phillips', 'aaron.phillips27@example.com', 2210),
    new SalesPerson('Bianca', 'Campbell', 'bianca.campbell28@example.com', 6360),
    new SalesPerson('Carl', 'Parker', 'carl.parker29@example.com', 540),
    new SalesPerson('Diana', 'Evans', 'diana.evans30@example.com', 4100),
    new SalesPerson('Ethan', 'Edwards', 'ethan.edwards31@example.com', 13330),
    new SalesPerson('Fiona', 'Collins', 'fiona.collins32@example.com', 7200),
    new SalesPerson('Gabe', 'Stewart', 'gabe.stewart33@example.com', 8050),
    new SalesPerson('Holly', 'Sanchez', 'holly.sanchez34@example.com', 2600),
    new SalesPerson('Ivan', 'Morris', 'ivan.morris35@example.com', 3900),
    new SalesPerson('Jade', 'Rogers', 'jade.rogers36@example.com', 14800),
    new SalesPerson('Kyle', 'Reed', 'kyle.reed37@example.com', 2750),
    new SalesPerson('Lily', 'Cook', 'lily.cook38@example.com', 5999),
    new SalesPerson('Mason', 'Morgan', 'mason.morgan39@example.com', 8400),
    new SalesPerson('Nora', 'Bell', 'nora.bell40@example.com', 1020),
    new SalesPerson('Owen', 'Murphy', 'owen.murphy41@example.com', 4310),
    new SalesPerson('Piper', 'Bailey', 'piper.bailey42@example.com', 6700),
    new SalesPerson('Quinn', 'Rivera', 'quinn.rivera43@example.com', 5555),
    new SalesPerson('Rose', 'Cooper', 'rose.cooper44@example.com', 4888),
    new SalesPerson('Sean', 'Richardson', 'sean.richardson45@example.com', 9200),
    new SalesPerson('Tara', 'Cox', 'tara.cox46@example.com', 3410),
    new SalesPerson('Ulysses', 'Howard', 'ulysses.howard47@example.com', 760),
    new SalesPerson('Vera', 'Ward', 'vera.ward48@example.com', 6120),
    new SalesPerson('Walt', 'Torres', 'walt.torres49@example.com', 9999),
    new SalesPerson('Xena', 'Peterson', 'xena.peterson50@example.com', 2899),
    new SalesPerson('Yuri', 'Gray', 'yuri.gray51@example.com', 7150),
    new SalesPerson('Zara', 'Ramirez', 'zara.ramirez52@example.com', 4300),
    new SalesPerson('Abel', 'James', 'abel.james53@example.com', 6575),
    new SalesPerson('Betty', 'Watson', 'betty.watson54@example.com', 3780),
    new SalesPerson('Chris', 'Brooks', 'chris.brooks55@example.com', 5020),
    new SalesPerson('Denise', 'Kelly', 'denise.kelly56@example.com', 8100),
    new SalesPerson('Eli', 'Sanders', 'eli.sanders57@example.com', 2250),
    new SalesPerson('Faith', 'Price', 'faith.price58@example.com', 9420),
    new SalesPerson('George', 'Bennett', 'george.bennett59@example.com', 10250),
    new SalesPerson('Hailey', 'Wood', 'hailey.wood60@example.com', 430),
    new SalesPerson('Isaac', 'Barnes', 'isaac.barnes61@example.com', 5200),
    new SalesPerson('Jasmine', 'Ross', 'jasmine.ross62@example.com', 6810),
    new SalesPerson('Kara', 'Henderson', 'kara.henderson63@example.com', 770),
    new SalesPerson('Liam', 'Coleman', 'liam.coleman64@example.com', 11900),
    new SalesPerson('Maya', 'Jenkins', 'maya.jenkins65@example.com', 3580),
    new SalesPerson('Noah', 'Perry', 'noah.perry66@example.com', 8999),
    new SalesPerson('Olivia', 'Powell', 'olivia.powell67@example.com', 1205),
    new SalesPerson('Peter', 'Long', 'peter.long68@example.com', 4600),
    new SalesPerson('Queenie', 'Patterson', 'queenie.patterson69@example.com', 7333),
    new SalesPerson('Ralph', 'Hughes', 'ralph.hughes70@example.com', 2480),
    new SalesPerson('Sofia', 'Flores', 'sofia.flores71@example.com', 5310),
    new SalesPerson('Trevor', 'Washington', 'trevor.washington72@example.com', 8540),
    new SalesPerson('Usha', 'Butler', 'usha.butler73@example.com', 2999),
    new SalesPerson('Viktor', 'Simmons', 'viktor.simmons74@example.com', 4100),
    new SalesPerson('Willa', 'Foster', 'willa.foster75@example.com', 6650),
    new SalesPerson('Ximena', 'Gonzales', 'ximena.gonzales76@example.com', 5175),
    new SalesPerson('Yosef', 'Bryant', 'yosef.bryant77@example.com', 2760),
    new SalesPerson('Zelda', 'Alexander', 'zelda.alexander78@example.com', 9800),
    new SalesPerson('Alan', 'Russell', 'alan.russell79@example.com', 4410),
    new SalesPerson('Bella', 'Griffin', 'bella.griffin80@example.com', 3700),
    new SalesPerson('Cody', 'Diaz', 'cody.diaz81@example.com', 2550),
    new SalesPerson('Darla', 'Hayes', 'darla.hayes82@example.com', 6040),
    new SalesPerson('Eamon', 'Myers', 'eamon.myers83@example.com', 980),
    new SalesPerson('Freya', 'Ford', 'freya.ford84@example.com', 14950),
    new SalesPerson('Gina', 'Hamilton', 'gina.hamilton85@example.com', 715),
    new SalesPerson('Hector', 'Graham', 'hector.graham86@example.com', 5390),
    new SalesPerson('Ivy', 'Sullivan', 'ivy.sullivan87@example.com', 4205),
    new SalesPerson('Jared', 'Wallace', 'jared.wallace88@example.com', 3333),
    new SalesPerson('Kendra', 'Woods', 'kendra.woods89@example.com', 8088),
    new SalesPerson('Logan', 'Cole', 'logan.cole90@example.com', 2777),
    new SalesPerson('Miriam', 'West', 'miriam.west91@example.com', 6230),
    new SalesPerson('Nolan', 'Jordan', 'nolan.jordan92@example.com', 5050),
    new SalesPerson('Opal', 'Owens', 'opal.owens93@example.com', 1999),
    new SalesPerson('Pablo', 'Reynolds', 'pablo.reynolds94@example.com', 7205),
    new SalesPerson('Renee', 'Fisher', 'renee.fisher95@example.com', 3330),
    new SalesPerson('Stella', 'Ellis', 'stella.ellis96@example.com', 4570),
    new SalesPerson('Ty', 'Harrison', 'ty.harrison97@example.com', 8888),
    new SalesPerson('Una', 'Guerra', 'una.guerra98@example.com', 2420),
    new SalesPerson('Vance', 'Burke', 'vance.burke99@example.com', 6123),
    new SalesPerson('Wren', 'Marshall', 'wren.marshall100@example.com', 7040)
  ];

  constructor() { }

  ngOnInit(): void {
  }

}
